### ISSUE TITLE
Support more CPU architectures

### ISSUE THREAD

**Issue by lilliliilil** [w0rng/amnezia-wg-easy#10]
The [ghcr page](https://ghcr.io/w0rng/amnezia-wg-easy) says arm64 is supported but it's not the case. It seems the issue is that amneziavpn/amnezia-wg [is being used as the base image](https://github.com/w0rng/amnezia-wg-easy/blob/1391267/Dockerfile#L16), which [doesn't support anything but amd64](https://hub.docker.com/r/amneziavpn/amnezia-wg/tags).

I spent quite some time today trying to make amnezia-wg-easy work on my arm64 server, figuring out what exactly is needed, building and etc. But fear not, now you don't have to do it yourself! So, here is the Dockerfile I ended up using in my compose config.

Someone needs to adapt it a little bit to make a proper PR, I might do it later myself if I find some time.

```Dockerfile
FROM alpine AS build-go
RUN apk add --no-cache git go make
RUN git clone https://github.com/amnezia-vpn/amneziawg-go.git
RUN cd amneziawg-go && make

FROM alpine AS build-c
RUN apk add --no-cache git build-base linux-headers
RUN git clone https://github.com/amnezia-vpn/amneziawg-tools.git
RUN cd amneziawg-tools/src && make

FROM alpine AS build-node
RUN apk add --no-cache git npm
RUN git clone https://github.com/w0rng/amnezia-wg-easy.git
RUN cd amnezia-wg-easy/src && npm ci --omit=dev

# ---

FROM alpine AS run
RUN apk add --no-cache bash nodejs dpkg iptables iptables-legacy
RUN update-alternatives \
  --install /usr/sbin/iptables iptables /usr/sbin/iptables-legacy 10 \
  --slave /usr/sbin/iptables-restore iptables-restore /usr/sbin/iptables-legacy-restore \
  --slave /usr/sbin/iptables-save iptables-save /usr/sbin/iptables-legacy-save

COPY --from=build-go /amneziawg-go/amneziawg-go /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg-quick/linux.bash /usr/local/bin/wg-quick
RUN mkdir /etc/amnezia && ln -s /etc/wireguard /etc/amnezia/amneziawg
RUN ln -s wg /usr/local/bin/awg

COPY --from=build-node /amnezia-wg-easy/src/wgpw.sh /usr/local/bin/wgpw
COPY --from=build-node /amnezia-wg-easy/src /app

WORKDIR /app
ENV DEBUG=Server,WireGuard
CMD ["node", "server.js"]
```

**Comment by alijazizaib** [comment]
Hey there, thanks for sharing this. I've been trying to set this up on an raspberry pi 5 but no luck.

I've tried to create an image from this dockerfile but run into an error:

```
`[+] Building 4.8s (12/23)                                                                                                  docker:default
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 1.36kB                                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                     1.5s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 57B                                                                                                     0.0s
 => [build-node 1/4] FROM docker.io/library/alpine:latest@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099    0.0s
 => CACHED [run  2/11] RUN apk add --no-cache bash nodejs dpkg iptables iptables-legacy                                              0.0s
 => CACHED [build-c 2/4] RUN apk add --no-cache git build-base linux-headers                                                         0.0s
 => CACHED [build-go 2/4] RUN apk add --no-cache git go make                                                                         0.0s
 => CACHED [build-node 2/4] RUN apk add --no-cache git npm                                                                           0.0s
 => CANCELED [build-go 3/4] RUN git clone https://github.com/amnezia-vpn/amneziawg-go.git                                            1.8s
 => CANCELED [build-node 3/4] RUN git clone https://github.com/w0rng/amnezia-wg-easy.git                                             2.9s
 => CANCELED [build-c 3/4] RUN git clone https://github.com/amnezia-vpn/amneziawg-tools.git                                          2.7s
 => ERROR [run  3/11] RUN update-alternatives   --install /sbin/iptables iptables /sbin/iptables-legacy 10   --slave /sbin/iptables  1.5s
------
 > [run  3/11] RUN update-alternatives   --install /sbin/iptables iptables /sbin/iptables-legacy 10   --slave /sbin/iptables-restore iptables-restore /sbin/iptables-legacy-restore   --slave /sbin/iptables-save iptables-save /sbin/iptables-legacy-save:
0.662 update-alternatives: error: alternative path /sbin/iptables-legacy doesn't exist
------
Dockerfile:21
--------------------
  20 |
  21 | >>> RUN update-alternatives \
  22 | >>>   --install /sbin/iptables iptables /sbin/iptables-legacy 10 \
  23 | >>>   --slave /sbin/iptables-restore iptables-restore /sbin/iptables-legacy-restore \
  24 | >>>   --slave /sbin/iptables-save iptables-save /sbin/iptables-legacy-save
  25 |
--------------------
ERROR: failed to solve: process "/bin/sh -c update-alternatives   --install /sbin/iptables iptables /sbin/iptables-legacy 10   --slave /sbin/iptables-restore iptables-restore /sbin/iptables-legacy-restore   --slave /sbin/iptables-save iptables-save /sbin/iptables-legacy-save" did not complete successfully: exit code: 2`
```

Not sure what is the issue. 

Could you share your steps on what you did with the Docker file? How did you run it? Thank you so much.

**Comment by 8176135** [comment]
I ran into the same issue, made a [fork here](https://github.com/8176135/amnezia-wg-easy) that fixes this, #8 and #12, (sadly didn't find this post first, so also wasted some time figuring out how to get it to build haha)

It also includes some default firewall changes I wanted to block traffic to LAN though, so you might have to remove that before using it if you want LAN access. 

Someone can probably remove those firewall changes and make a PR.

FYI @alijazizaib

**Comment by alijazizaib** [comment]
I'll try your fork and provide updates if it works for me. Thank you for your input!!

**Comment by zixstas** [comment]
I also managed to launch it, I spent 4 DAYS on launching it: 
`# Этап для сборки Node.js приложения
FROM alpine:latest AS build-node
RUN apk add --no-cache git npm
RUN git clone https://github.com/w0rng/amnezia-wg-easy.git
WORKDIR /amnezia-wg-easy/src
RUN npm ci --omit=dev

# Этап для сборки Go приложения
FROM alpine:latest AS build-go
RUN apk add --no-cache git go make
RUN git clone https://github.com/amnezia-vpn/amneziawg-go.git
WORKDIR /amneziawg-go
RUN make

# Этап для сборки C утилит
FROM alpine:latest AS build-c
RUN apk add --no-cache git build-base linux-headers
RUN git clone https://github.com/amnezia-vpn/amneziawg-tools.git
WORKDIR /amneziawg-tools/src
RUN make

# Основной этап для запуска приложения
FROM alpine:latest AS run
RUN apk add --no-cache bash nodejs dpkg iptables

# Настройка iptables (используем iptables-nft вместо iptables-legacy)
RUN ln -s /sbin/iptables-nft /sbin/iptables && \
    ln -s /sbin/iptables-nft-restore /sbin/iptables-restore && \
    ln -s /sbin/iptables-nft-save /sbin/iptables-save

# Копирование собранных бинарных файлов
COPY --from=build-go /amneziawg-go/amneziawg-go /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg-quick/linux.bash /usr/local/bin/wg-quick

# Создание необходимых директорий и симлинков
RUN mkdir -p /etc/amnezia && ln -s /etc/wireguard /etc/amnezia/amneziawg
RUN ln -s /usr/local/bin/wg /usr/local/bin/awg

# Копирование скриптов и приложения
COPY --from=build-node /amnezia-wg-easy/src/wgpw.sh /usr/local/bin/wgpw
COPY --from=build-node /amnezia-wg-easy/src /app

# Установка рабочей директории
WORKDIR /app

# Установка переменных окружения
ENV DEBUG=Server,WireGuard

# Команда для запуска приложения
CMD ["node", "server.js"]`

**Comment by zixstas** [comment]
I also managed to launch it, I spent 4 DAYS on launching it:
FROM alpine:latest AS build-node
RUN apk add --no-cache git npm
RUN git clone https://github.com/w0rng/amnezia-wg-easy.git
WORKDIR /amnezia-wg-easy/src
RUN npm ci --omit=dev


FROM alpine:latest AS build-go
RUN apk add --no-cache git go make
RUN git clone https://github.com/amnezia-vpn/amneziawg-go.git
WORKDIR /amneziawg-go
RUN make


FROM alpine:latest AS build-c
RUN apk add --no-cache git build-base linux-headers
RUN git clone https://github.com/amnezia-vpn/amneziawg-tools.git
WORKDIR /amneziawg-tools/src
RUN make


FROM alpine:latest AS run
RUN apk add --no-cache bash nodejs dpkg iptables


RUN ln -s /sbin/iptables-nft /sbin/iptables && \
    ln -s /sbin/iptables-nft-restore /sbin/iptables-restore && \
    ln -s /sbin/iptables-nft-save /sbin/iptables-save


COPY --from=build-go /amneziawg-go/amneziawg-go /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg /usr/local/bin
COPY --from=build-c /amneziawg-tools/src/wg-quick/linux.bash /usr/local/bin/wg-quick


RUN mkdir -p /etc/amnezia && ln -s /etc/wireguard /etc/amnezia/amneziawg
RUN ln -s /usr/local/bin/wg /usr/local/bin/awg


COPY --from=build-node /amnezia-wg-easy/src/wgpw.sh /usr/local/bin/wgpw
COPY --from=build-node /amnezia-wg-easy/src /app


WORKDIR /app


ENV DEBUG=Server,WireGuard

CMD ["node", "server.js"]

**Comment by alijazizaib** [comment]
So I managed to get your fork work though it required some tweaking @8176135 

Here's how it went:

1. I cloned your repository into my Raspberry Pi 5 home directory. Note I am running a stock fresh install of  the latest Raspbian OS 64bit. 
2. Then I ran the following code as per the readme:
```
sudo docker run -d \
  --name=amnezia-wg-easy \
  -e LANG=en \
  -e WG_HOST=<Public IP> \
  -e PASSWORD_HASH=`<Hash>`\
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.amnezia-wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --device=/dev/net/tun:/dev/net/tun \
  --restart unless-stopped \
  ghcr.io/w0rng/amnezia-wg-easy
```
3. This didn't work. The docker server kept restarting and I figured it was the same error. The reason this was failing was because it pulled the original image instead. 
4. I ran into this error as this is my first time using Docker and I am still figuring out how to use it. I understood that @8176135 had modified the Dockerfile and this required a new image to be built.
5. I used the Docker Build command to build a new image. This required me to use some Deepseek to help me explain the commands and troubleshoot. 
6. Once the new image was built, I ran the following command to run the container:
```
sudo docker run -d \
  --name=amnezia-wg-easy \
  -e LANG=en \
  -e WG_HOST=<Public IP> \
  -e PASSWORD_HASH=`<Hash>`\
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.amnezia-wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --device=/dev/net/tun:/dev/net/tun \
  --restart unless-stopped \
  amnezia-wg-easy:latest #This was the name of the docker image I built using the Docker Build command
```
7. The container didn't run properly still. When I checked `docker ps`, it kept restarting with error code 1. I then used `docker logs amnezia-wg-easy` to check the logs and found the following error log:
```
2025-01-28T06:25:42.977Z Server Listening on http://0.0.0.0:51821
2025-01-28T06:25:42.984Z WireGuard Loading configuration...
$ wg genkey
$ echo ***hidden*** | wg pubkey
2025-01-28T06:25:42.995Z WireGuard Configuration generated.
2025-01-28T06:25:42.996Z WireGuard Config saving...
node:internal/fs/promises:638
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/etc/amnezia/amneziawg/wg0.json'
    at async open (node:internal/fs/promises:638:25)
    at async Object.writeFile (node:internal/fs/promises:1208:14)
    at async WireGuard.__saveConfig (/app/lib/WireGuard.js:154:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:91:7)
    at async WireGuard.cronJobEveryMinute (/app/lib/WireGuard.js:440:20)
    at async cronJobEveryMinute (/app/lib/Server.js:69:3) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/etc/amnezia/amneziawg/wg0.json'
}

Node.js v22.11.0
```
8. Upon troubleshooting, I found that I needed to uncomment the following line (line 72) from the Dockerfile. @8176135  Any idea why was this commented out?
```
# Make the default dir for wg0.conf
RUN mkdir -p /etc/amnezia/amneziawg/
```
9. After this, I re-built a new Docker image and ran the server using the command in step 6. Then the container worked without errors and I could access the Wg easy dashboard without any issues. 

Documented my process here in case anyone runs into the same issues I have. Thank you so much for the help everyone. The next step I'd like to do is to run [Wiregate](https://github.com/NOXCIS/Wiregate). If anyone has managed to run that on Arm, could you share your method? I think it's gonna be quite similar to the way this issue was resolved.

**Comment by 8176135** [comment]
> 8. Upon troubleshooting, I found that I needed to uncomment the following line (line 72) from the Dockerfile. @8176135 Any idea why was this commented out?

Have a look at the readme change I did: https://github.com/8176135/amnezia-wg-easy/commit/bf4e1803bbcab475bcd4f5d6de552fefee832612

There probably should be a better error message there, but it is commented out because it is meant to error to warn you that you are meant to mount that directory to a volume, this way when you restarted the docker container, all of the clients you added will still be there.

Right now, if you restart, I think all the clients will get wiped.

I might setup some auto build workflow to push the container image up so you don't have to build it yourself when I get time to avoid 4. happening.

**Comment by alijazizaib** [comment]
Ah I missed out that change you did in the docker run command >.<. 

Thank you for explaining it. So essentially I have to learn how to mount a volume to the docker container to keep the .conf files. 

Let me see if I can do that.

**Comment by alijazizaib** [comment]
Okay. The original issue I was having regarding the Wg0.conf path not being found has been resolved after I fixed my docker run command. I don't need to rebuild the Docker image and can use the image built from @8176135 's Dockerfile.

**Comment by s1dave-web** [comment]
+1 wanted to try this out with my Oracle host but got exec errors.

Would be nice to be able to spin up in portainer easily on arm device.

**Comment by alijazizaib** [comment]
@s1dave-web 
Try the fork from @8176135 , it works fine for me now on Raspberry Pi 5. I haven't tried on older Pi models.

**Comment by lilliliilil** [comment]
I updated the op post, it should work again.
