### ISSUE TITLE
Getting error running on Centos7, but normal wg-easy works well.

### ISSUE THREAD

**Issue by PenzinAlexander** [w0rng/amnezia-wg-easy#3]
Trying to run this with docker-compose. Getting the error. But normal wg-easy works fine. Any workaround?

```Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:95:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:93:7)
    at async WireGuard.cronJobEveryMinute (/app/lib/WireGuard.js:449:20)
    at async cronJobEveryMinute (/app/lib/Server.js:69:3)
    ```

**Comment by w0rng** [comment]
The base Docker image used is https://hub.docker.com/r/amneziavpn/amnezia-wg.

The issue might be related to CentOS support in this project. It's difficult to provide a more detailed answer without the full stack trace.

**Comment by oglodyte** [comment]
Same issue with Ubuntu 20.04.6 host. Also working wg-easy:

2024-10-25T05:54:06.253Z Server Listening on http://0.0.0.0:51821
2024-10-25T05:54:06.259Z WireGuard Loading configuration...
2024-10-25T05:54:06.263Z WireGuard Configuration loaded.
2024-10-25T05:54:06.263Z WireGuard Config saving...
2024-10-25T05:54:06.265Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
/app/lib/WireGuard.js:95
          throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
                ^
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:95:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:93:7)
    at async WireGuard.cronJobEveryMinute (/app/lib/WireGuard.js:440:20)
    at async cronJobEveryMinute (/app/lib/Server.js:69:3)

**Comment by alfonder** [comment]
@oglodyte @PenzinAlexander  you need to compile the kernel module amneziawg.ko onto  the host system (or install dkms package to do it automatically). For all supported Ubuntu versions they definitely exist. For CentOS I don't know, you need to check AmneziaWG project.

**Comment by nktnet1** [comment]
> The base Docker image used is https://hub.docker.com/r/amneziavpn/amnezia-wg.
> 
> The issue might be related to CentOS support in this project. It's difficult to provide a more detailed answer without the full stack trace.

Could be related to #12 - the base image should be updated to [amneziawg-go](https://hub.docker.com/r/amneziavpn/amneziawg-go)
